### ISSUE TITLE
Incompatible Spring boot 2.2.5.RELEASE

### ISSUE THREAD

**Issue by fabriciolfj** [svenkubiak/embedded-mongodb#2]
Ao utilizar a dependencia com a versão do spring bott 2.2.5, ocorre o erro abaixo:
`java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.impl.SimpleLoggerFactory loaded from file:/home/projeto/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.30/e606eac955f55ecf1d8edcccba04eb8ac98088dd/slf4j-simple-1.7.30.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.impl.SimpleLoggerFactory`

**Comment by svenkubiak** [comment]
This library ships with slf4j-simple for logging. 
Recommended workaround:

```
 <dependency>
  <groupId>de.svenkubiak</groupId>
  <artifactId>embedded-mongodb</artifactId>
  <version>5.0.5</version>
    <exclusions>
      <exclusion>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
     </exclusion>
    </exclusions>
</dependency>
```

OR

https://www.baeldung.com/spring-boot-embedded-mongodb
