### ISSUE TITLE
Add support for $expr

### ISSUE THREAD

**Issue by haiderali22** [svenkubiak/embedded-mongodb#3]
When running test case which uses $expr (https://docs.mongodb.com/manual/reference/operator/aggregation/exp/) following error is thrown 

> Caused by: com.mongodb.MongoCommandException: Command failed with error 2 (BadValue): 'unknown top level operator: $expr' on server localhost:22632. The full response is {"ok": 0.0, "errmsg": "unknown top level operator: $expr", "code": 2, "codeName": "BadValue"}

**Comment by 6mo** [comment]
You are probably using the default version of mongodb: "3.5.5"

To use the version 4, try this in your configuration:
`spring.mongodb.embedded.version = 4.0.2`
